### ISSUE TITLE
Data Interface to new ESCs (Talon SRX)

### ISSUE THREAD

**Issue by ghost** [ISU-MAVRIC/MAVRIC-Systems#18]
The [Talon SRX](https://www.vexrobotics.com/217-8080.html) units have 2 interface options. We can get access to internal PID control by using CAN bus.

**Comment by Talonj123** [comment]
I don't know if the PID only uses an external sensor, or if it can use something with the motor current draw. I'm not envisioning this really mattering for us. The only case I can think of where it would is if we needed to know the speed of each wheel for diagnostics.
