### ISSUE TITLE
Weight reduction

### ISSUE THREAD

**Issue by ghost** [ISU-MAVRIC/MAVRIC-Systems#23]
As the Rover needs to be light, we should think of ways to reduce electronics weight.

# 'Free' items
These are items that do not negatively impact performance.
 - [ ] Clean up suspension wiring (reduce excess length
   - Savings unknown

# Trade-off items
These items may reduce performance/capacity but also reduce weight. More analysis is needed before deciding to do them (add sub-bullets with information)
 - [ ] Replace 5V regulators with 3A BEC units.
   - Each Pi consumes up to ~500mA (full load)
   - 3A units seem to be smaller than the ones we use, and should safely power 4 Pi's (needs testing)
 - [ ] Reduce wire size
   - Evaluate the sizes and loads of each of our wires (particularly our 8-AWG wires). We want to keep enough capacity to handle the max current, but we rarely if ever use the maximum possible current.

# Unclassified
Put ideas that may or may not impact performance here.

**Comment by Talonj123** [comment]
We can safely go as small as 22 AWG for the arm actuator, which would be the lightest option. We should probably also put all those wires in one locking connector.

http://www.powerstream.com/Wire_Size.htm
