### ISSUE TITLE
Battery Voltage Monitor

### ISSUE THREAD

**Issue by ghost** [ISU-MAVRIC/MAVRIC-Systems#26]
We need to measure the voltage of the batteries.

**Comment by Talonj123** [comment]
The [pimoroni Automation pHAT](https://www.adafruit.com/product/3289) has a 24V ADC, which would work for anything less than 6S. We are using a 6S battery for the drive system, so we will need a voltage divider anyways.

We might be able to get away with using the 24V ADC as long as we are okay with not knowing the difference between 90% charged and 100% charged. THe battery is usually around 23V, and is only above 24V for a short time. We could do a resistor and a diode string or something if the board is not internally tolerant of 25.2V (6S LiPo pack maximum)

**Comment by Talonj123** [comment]
Will Rickert is designing a board for us.
