### ISSUE TITLE
RM5 connection characteristics

### ISSUE THREAD

**Issue by ghost** [ISU-MAVRIC/MAVRIC-Systems#30]
We should know the RM5's connection characteristics:
 - Minimum Range
 - Maximum Range
 - Connection time
 - Effects of range on connection time
 - Effects of weather on connection time?
 - Effective (empirical) throughput at various ranges

**Comment by Talonj123** [comment]
To collect some of these will be rather difficult in the lab. We may even need a road trip.

**Comment by Talonj123** [comment]
Drive testing outdoors showed that we tend to lose connection when there are buildings in the way. We can go from the south side Hub to the steps of Curtis with no problems though.
