### ISSUE TITLE
Main camera

### ISSUE THREAD

**Issue by ghost** [ISU-MAVRIC/MAVRIC-Systems#34]
It might be http://www.accessories-shops.com/sony-camera-series/cctv-sony-camera-zoom-module-fcb-ex45cp-colour.html

We do know it supports the VISCA protocol for commands like zooming in and out. None of the wires coming out of the camera are labeled/color coded, so we really don't want to have to redo those.

That is all I know.

**Comment by Talonj123** [comment]
We think we found it: https://www.aegis-elec.com/media/wysiwyg/pdf/FCB-EX1010.compressed.pdf

**Comment by Talonj123** [comment]
We have a 1.2 GHz trainmitter/receiver pair. I am concerned about the range though, we need to get it running (requires RCA cable) and do some testing.

Alternatively, we can switch to digital with adapter boards (price unknown).

**Comment by Talonj123** [comment]
I have contacted stemmer about one of these boards, https://www.stemmer-imaging.co.uk/en/products/series/sony-fcb-interfaces/. We will see what details they can give us.

**Comment by Talonj123** [comment]
As far as I can tell, we'll need one of these to provide power and get video out (I think we want the VBS pin for analog):
KYOCERA ELCO 00 6200 509 130 000+

**Comment by Talonj123** [comment]
The board from above does not support our camera, but there is another one that might:
[Atomas-Mini-LVDS](http://imaging.ionodes.com/atomas-mini-lvds)

**Comment by Talonj123** [comment]
I am trying to get a response from some sales people who think they can help
