### ISSUE TITLE
New Components List

### ISSUE THREAD

**Issue by ghost** [ISU-MAVRIC/MAVRIC-Systems#35]
# Things we need/want to get:
## Regulators (enhancement)
Our current regulators are a bit heavy and have unknown thermal characteristics.
Loads:
 - 1A per Pi + ~0.5 for HATs. I'd like to reserve 2A per Pi. 4 Pis => 8A @ 5V
 - 1.5 A peak/fan x 8 fans => 12A peak @ 12V, 6A continuous
 - Network switch rated for 1A @ 24V and switch 1A@12V, so total 3A @ 12V 
 - Camera Servos 1.8A each => 3.6A @ 6V

I would like to keep all these separate.

## Sensors (mixed)
We need some additional sensors:
 - ADC for battery voltage (requirement)
 - [LiDAR](https://www.sparkfun.com/products/14032)/other reliable rangefinder (enhancement)
 - Current monitors for various power rails in the E-Box (see regulators section) and beyond (up to 60A combined for wheels, unknown for the arm). (enhancement)

## Actuators
 - Relay for Software E-Stop. Has to handle total E-box load (before regulators). Currently estimated at about 10.5A peak for a 22.2V battery (230W). (enhancement)
 - Screen of some sort (check rules to see if we can use one to leave messages for the field team). E-Ink should be visible in daylight. (enhancement
 - Lights/other indicators to indicate when we reach autonomous waypoints. (requirement, I think)

## Miscellaneous
 - 12V power rail for the arm
   - we could make another bus bar, but that might be overkill, a terminal block might be sufficient. I'd prefer to avoid a octopus cable if possible, though I could go for a sealed bar by the arm.
 - 2x Raspberry Pi 3B.
   - We need these for the science and arm board. It is possible to use just one since only one of those systems will be attached, but it makes everything more complicated.
 - [POE injectors for the RM5 and camera](https://www.amazon.com/iCreatin-Passive-Injector-Splitter-Connector/dp/B00NRHNPUA/ref=sr_1_5?ie=UTF8&qid=1533845853&sr=8-5&keywords=dc+poe+injector)

**Comment by Talonj123** [comment]
Some regulator options:
 - [Our current ones](https://www.aliexpress.com/item/DC-Adjustable-Voltage-Regulator-Module-DC-4-5-30V-to-0-8-30V-12A-Buck-Converters/1724570414.html)
   - Price/Amp: $0.75
   - Weight: ???
 - [KNACRO unit](https://www.amazon.com/KNACRO-Waterproof-Converter-Regulator-Transformer/dp/B073XCC1GR/ref=sr_1_14?ie=UTF8&qid=1533429630&sr=8-14&keywords=5v+10a+regulator)
   - Price/amp: $1.06
   - Weight: 60g
   - Sealed: yes
 - [BINZET unit](https://www.amazon.com/BINZET-Converter-Regulator-Regulated-Transformer/dp/B00J3MHTYG/ref=sr_1_9?ie=UTF8&qid=1533429871&sr=8-9&keywords=24V+to+5v+10a+regulator)
   - Price/Amp: $1.10
   - Weight: ???
   - Sealed: yes

**Comment by Talonj123** [comment]
ADC Options:
 - [12-bit 4-channel breakout board](https://learn.adafruit.com/raspberry-pi-analog-to-digital-converters/ads1015-slash-ads1115)
   - Python Library: Yes
