### ISSUE TITLE
Spending

### ISSUE THREAD

**Issue by ghost** [ISU-MAVRIC/MAVRIC-Systems#40]
In addition to #35.

 - [Li-Ion one](http://www.batterysupports.com/22v-252v-1818650-7800mah-6s3p-lithium-ion-liion-battery-pack-p-141.html)
   - $85
   - Should have 2 available for charging one while the other is in use.

- Lighter material for the E-box (not big as most of the weight is from other stuff)

**Comment by Talonj123** [comment]
@GageLochner
