### ISSUE TITLE
RasPi auto-update

### ISSUE THREAD

**Issue by ghost** [ISU-MAVRIC/MAVRIC-Systems#42]
our Ubuntu distro has an auto-updater that sometimes locks things up. we should probably disable this.

**Comment by Talonj123** [comment]
See https://linoxide.com/ubuntu-how-to/enable-disable-unattended-upgrades-ubuntu-16-04/.

It comes down to editing `/etc/apt/apt.conf.d/10periodic` and changing
`APT::Periodic::Update-Package-Lists "1";` to `APT::Periodic::Update-Package-Lists "0";`
