### ISSUE TITLE
Antennas

### ISSUE THREAD

**Issue by ghost** [ISU-MAVRIC/MAVRIC-Systems#43]
Depending on the results of range tests, we may need to look into other antenna systems. With point-to-point line-of-sight operation, the RM5 transceivers can go up to at least 70 km with parabolic antennas.

**Comment by Talonj123** [comment]
Sector antenna option (3x range boost?):
https://store.ubnt.com/collections/wireless/products/5ghz-airmax-basestation-19dbi-120-deg-rocket-kit
