### ISSUE TITLE
1.2 GHz Video Transmitter

### ISSUE THREAD

**Issue by ghost** [ISU-MAVRIC/MAVRIC-Systems#45]
The transmitter was run off of 18V or so last time we went to competition, it is rated for 12. It gets really hot, even with a heatsink, which could be because of damage.

**Comment by Talonj123** [comment]
We can replace [the pair](https://www.amazon.com/Hikity-Updated-Wireless-Transmitter-Receiver/dp/B073Y1LKZG/ref=sr_1_3?ie=UTF8&qid=1538596318&sr=8-3&keywords=1.2+ghz+transmitter&dpID=41w20uPeVfL&preST=_SY300_QL70_&dpSrc=srch) for $60 (same units) or get a [3W version](https://www.amazon.com/SainSonic-2-4GHz-Wireless-Transmitter-Receiver/dp/B00G4S2CR6/ref=sr_1_5?ie=UTF8&qid=1538596318&sr=8-5&keywords=1.2+ghz+transmitter&dpID=31V%252BzOaVpqL&preST=_SY300_QL70_&dpSrc=srch) (old is 2W) for 77$
